"use client";

import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, Package, ReceiptText, TrendingUp, Users, Wallet } from "lucide-react";
import Link from "next/link";

type Summary = { todaySales: number; todayGrossProfit: number; todayTransactions: number; averageTicket: number; totalProducts: number; totalCustomers: number; lowStockCount: number; salesOverview: Array<{ date: string; total: number; transactions: number }>; topProducts: Array<{ productName: string; productSku: string; _sum: { quantity: number | null; subtotal: number | string | null } }>; recentSales: Array<{ id: number; receiptNumber: string; total: number | string; createdAt: string; client: { name: string } | null }> };
const money = (value: number | string) => new Intl.NumberFormat("es-EC", { style: "currency", currency: "USD" }).format(Number(value));

export default function HomePage() {
  const summary = useQuery<Summary>({ queryKey: ["dashboard-summary"], queryFn: async () => { const res = await fetch("/api/dashboard/summary"); if (!res.ok) throw new Error(); return res.json(); }, staleTime: 30_000 });
  const data = summary.data;
  const stats = [["Ventas de hoy", data?.todaySales, Wallet, "bg-violet-100 text-violet-700", true], ["Ganancia estimada", data?.todayGrossProfit, TrendingUp, "bg-emerald-100 text-emerald-700", true], ["Transacciones hoy", data?.todayTransactions, ReceiptText, "bg-blue-100 text-blue-700", false], ["Ticket promedio", data?.averageTicket, TrendingUp, "bg-amber-100 text-amber-700", true]] as const;
  const maxSale = Math.max(...(data?.salesOverview.map((item) => item.total) ?? [1]), 1);
  return <div className="space-y-6 pb-8">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold text-purple-600">RESUMEN OPERATIVO</p><h1 className="text-3xl font-bold tracking-tight text-gray-900">Dashboard</h1><p className="mt-1 text-sm text-gray-500">El rendimiento de tu papelería hoy.</p></div><Link href="/sales" className="inline-flex items-center justify-center rounded-xl bg-purple-700 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-purple-200 hover:bg-purple-800"><ReceiptText className="mr-2 h-4 w-4" />Nueva venta</Link></header>
    {summary.isError ? <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-red-700">No se pudo cargar el resumen. Intenta actualizar la página.</div> : <>
      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value, Icon, accent, isMoney]) => <article key={label} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-theme-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-gray-500">{label}</p><p className="mt-3 text-3xl font-bold text-gray-900">{summary.isLoading ? "—" : isMoney ? money(value ?? 0) : value ?? 0}</p></div><span className={`rounded-xl p-3 ${accent}`}><Icon className="h-5 w-5" /></span></div><p className="mt-3 text-xs text-emerald-600">Actualizado en tiempo real</p></article>)}</section>
      <section className="grid gap-6 xl:grid-cols-[1.4fr_0.85fr]"><article className="rounded-2xl border border-gray-100 bg-white p-6 shadow-theme-sm"><h2 className="font-bold text-gray-900">Evolución de ventas</h2><p className="text-sm text-gray-500">Últimos 7 días</p><div className="mt-8 flex h-52 items-end gap-3">{(data?.salesOverview ?? []).map((item) => <div key={item.date} className="flex flex-1 flex-col items-center gap-2"><div className="flex h-44 w-full items-end rounded-t-lg bg-violet-50"><div className="w-full rounded-t-lg bg-gradient-to-t from-purple-700 to-violet-400" style={{ height: `${Math.max(item.total ? (item.total / maxSale) * 100 : 2, 2)}%` }} /></div><span className="text-[10px] text-gray-500">{new Date(`${item.date}T12:00:00`).toLocaleDateString("es-EC", { weekday: "short" })}</span></div>)}</div></article><article className="rounded-2xl border border-gray-100 bg-white p-6 shadow-theme-sm"><h2 className="font-bold text-gray-900">Top productos</h2><p className="text-sm text-gray-500">Más vendidos hoy</p><div className="mt-5 space-y-4">{data?.topProducts.length ? data.topProducts.map((item, index) => <div key={item.productSku} className="flex items-center gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-violet-100 text-xs font-bold text-purple-700">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-gray-800">{item.productName}</p><p className="text-xs text-gray-500">{item._sum.quantity ?? 0} unidades</p></div><p className="text-sm font-bold">{money(item._sum.subtotal ?? 0)}</p></div>) : <p className="py-10 text-center text-sm text-gray-500">Aún no hay ventas hoy.</p>}</div></article></section>
      <section className="grid gap-6 xl:grid-cols-[1.4fr_0.85fr]"><article className="rounded-2xl border border-gray-100 bg-white p-6 shadow-theme-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold text-gray-900">Ventas recientes</h2><p className="text-sm text-gray-500">Últimos recibos registrados</p></div><Link href="/sales" className="text-sm font-semibold text-purple-700">Ver historial</Link></div><div className="mt-5 divide-y divide-gray-100">{data?.recentSales.length ? data.recentSales.map((sale) => <div key={sale.id} className="flex items-center justify-between py-3"><div><p className="text-sm font-bold text-gray-800">#{sale.receiptNumber}</p><p className="text-xs text-gray-500">{sale.client?.name ?? "Consumidor Final"}</p></div><p className="font-bold text-gray-900">{money(sale.total)}</p></div>) : <p className="py-10 text-center text-sm text-gray-500">Crea tu primera venta para verla aquí.</p>}</div></article><article className="rounded-2xl border border-amber-100 bg-amber-50 p-6"><div className="flex items-center gap-3"><span className="rounded-xl bg-amber-200 p-2 text-amber-800"><AlertTriangle className="h-5 w-5" /></span><div><h2 className="font-bold text-gray-900">Inventario bajo</h2><p className="text-sm text-gray-600">Productos que requieren atención</p></div></div><p className="mt-6 text-4xl font-bold text-amber-900">{data?.lowStockCount ?? "—"}</p><p className="mt-1 text-sm text-amber-800">productos en o bajo el mínimo configurado.</p><Link href="/products" className="mt-6 inline-flex text-sm font-bold text-amber-900 underline">Revisar inventario</Link><div className="mt-6 grid grid-cols-2 gap-3 border-t border-amber-200 pt-5"><div><Users className="h-4 w-4 text-purple-600" /><p className="mt-1 text-lg font-bold">{data?.totalCustomers ?? "—"}</p><p className="text-xs text-gray-600">Clientes</p></div><div><Package className="h-4 w-4 text-purple-600" /><p className="mt-1 text-lg font-bold">{data?.totalProducts ?? "—"}</p><p className="text-xs text-gray-600">Productos</p></div></div></article></section>
    </>}
  </div>;
}
