"use client";

import { useQuery } from "@tanstack/react-query";
import { Eye, PackageSearch, Search, X } from "lucide-react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { getProductsPage } from "@/services/productService";

export default function GlobalProductSearch() {
  const [value, setValue] = useState(""); const [term, setTerm] = useState(""); const [open, setOpen] = useState(false); const ref = useRef<HTMLDivElement>(null); const input = useRef<HTMLInputElement>(null); const router = useRouter();
  useEffect(() => { const timer = window.setTimeout(() => setTerm(value.trim()), 200); return () => window.clearTimeout(timer); }, [value]);
  useEffect(() => { const keyboard = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); input.current?.focus(); setOpen(true); } if (event.key === "Escape") setOpen(false); }; document.addEventListener("keydown", keyboard); return () => document.removeEventListener("keydown", keyboard); }, []);
  useEffect(() => { const outside = (event: MouseEvent) => { if (ref.current && !ref.current.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", outside); return () => document.removeEventListener("mousedown", outside); }, []);
  const results = useQuery({ queryKey: ["global-product-search", term], queryFn: () => getProductsPage({ search: term, page: 1, pageSize: 6 }), enabled: term.length >= 2, staleTime: 10_000 });
  const select = (id: number) => { setOpen(false); setValue(""); router.push(`/sales?product=${id}`); };
  const viewDetails = (id: number) => { setOpen(false); setValue(""); router.push(`/products?product=${id}`); };
  return <div ref={ref} className="relative hidden min-w-0 flex-1 lg:block lg:max-w-2xl xl:max-w-3xl"><Search className="pointer-events-none absolute left-4 top-1/2 z-10 h-5 w-5 -translate-y-1/2 text-slate-400" /><input ref={input} value={value} onFocus={() => setOpen(true)} onChange={(event) => setValue(event.target.value)} placeholder="Buscar producto por nombre, SKU o código de barras…" className="h-13 w-full rounded-2xl bg-slate-100 pl-12 pr-20 text-base font-medium text-slate-700 outline-none transition focus:bg-white focus:ring-4 focus:ring-purple-100" /><span className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg bg-white px-2 py-1.5 text-xs font-bold text-slate-500">⌘ K</span>{value && <button onClick={() => { setValue(""); input.current?.focus(); }} className="absolute right-16 top-1/2 -translate-y-1/2 text-slate-400"><X className="h-5 w-5" /></button>}{open && term.length >= 2 && <div className="absolute left-0 top-14 z-[100000] w-full overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-2xl"><div className="border-b border-slate-100 px-4 py-3 text-xs font-semibold text-slate-500">PRODUCTOS</div>{results.isLoading ? <p className="px-4 py-5 text-sm text-slate-500">Buscando…</p> : results.data?.data.length ? results.data.data.map((product) => <div key={product.id} className="flex items-center gap-2 border-b border-slate-50 px-2 last:border-0 hover:bg-violet-50"><button onClick={() => select(product.id)} className="flex min-w-0 flex-1 items-center gap-3 px-2 py-3 text-left"><Image src={product.image || "/placeholder.svg"} alt="" width={40} height={40} className="h-10 w-10 rounded-lg object-cover" /><span className="min-w-0 flex-1"><span className="block truncate text-base font-bold text-slate-800">{product.name}</span><span className="block text-sm text-slate-500">SKU: {product.sku} · Stock: {product.quantity}</span></span><span className="text-base font-bold text-purple-700">${Number(product.price).toFixed(2)}</span></button><button type="button" onClick={() => viewDetails(product.id)} className="rounded-xl p-2.5 text-slate-500 transition hover:bg-white hover:text-purple-700" aria-label={`Ver detalle de ${product.name}`} title="Ver detalle"><Eye className="h-5 w-5" /></button></div>) : <div className="px-4 py-6 text-center text-sm text-slate-500"><PackageSearch className="mx-auto mb-2 h-5 w-5" />No hay coincidencias.</div>}<div className="border-t border-slate-100 px-4 py-3 text-xs text-slate-400">Haz clic para agregar al POS · usa el ojo para ver el detalle.</div></div>}</div>;
}
